const formField = {
    分中心:"fenzhongxin",
    住院号:"zhuyuanhao",
    姓名:"xingming",
    住院次数: "zhuyuancishu",
    // 性别: "xingbie",
    // 年龄: "nianling",
    // 出生日期: "chushengriqi",
    // 国籍: "guoji",
    // 病人籍贯: "jiguan",
    // 民族: "minzu",
    // 身份证号: "shenfenzhenghao",
    // 职业: "zhiye",
    // 住址: "zhuzhi",
    // 联系电话: "lianxidianhua",
    入院途径: "ruyuantujing",
    住院天数: "zhuyuantianshu",
    入院科别: "ruyuankebie",
    转科科别: "zhuankekebie",
    出院科别: "chuyuankebie",
    主要诊断: "zhuyaozhenduan",
    主要诊断编码: "zhuyaozhenduanbianma",
    其他诊断: "qitazhenduan",
    其他诊断编码: "qitazhenduanbianma",

    发病时间: "fabingshijian",
    主要症状: "zhuyaozhengzhuang",
    伴随症状: "bansuizhengzhuang",
    既往史: "jiwangshi",
    药物过敏: "yaowuguomin",
    过敏药物: "guominyaowu",
    吸烟史: "xiyanshi",
    饮酒史: "yinjiushi",
    个人史: "gerenshi",
    家族史: "jiazushi",


    血压: "xueya",
    意识水平: 'yishishuiping',
    肢体运动肌力: "zhitiyundongjili",
    感觉障碍: "ganjuezhangai",
    语言表达: "yuyanbiaoda",
    神经反射: "shenjingfanshe",
    病理征: "binglizheng",
    NIHSS: "NIHSS",
    GLASGOW: "GLASGOW",
    ADL: "ADL",
    MRANKIN: "MRANKIN",
    MMSE: "MMSE",
    LOTCA: "LOTCA",

    颅内出血部位: "chuxuebuwei",
    颅内出血体积: "chuxuetiji",
    CT值: "CTzhi",
    心脏彩超: "xinzangcaichao",
    LVEF: "LVEF",
    颈动脉彩超: "jingdongmaicaichao",
    胸片: "xiongpian",

    白细胞: "xuebaixibao",
    中性细胞数: "zhongxing",
    淋巴细胞数: "linba",
    单核细胞: "danhe",
    红细胞数: "xuehongxibao",
    血红蛋白: "xuehongdanbai",
    血小板: "xuexiaoban",

    尿白细胞: "niaobaixibao",
    尿红细胞: "niaohongxibao",
    尿蛋白: "niaodanbai",
    脓细胞: "nongxibao",

    OB: "OB",

    谷丙转氨酶: "gubing",
    谷草转氨酶: "gucao",
    转肽酶: "zhuantaimei",
    总蛋白: "zongdanbai",
    白蛋白: "baidanbai",
    总胆红素: "zongdanhongsu",
    直接胆红素: "zhijiedanhongsu",
    血糖: "xuetang",
    总胆固醇: "zongdanguchun",
    甘油三脂: "ganyousanzhi",
    HDL: "HDL",
    LDL: "LDL",
    糖化血红蛋白: "tanghuaxuehongdanbai",
    HCY: "HCY",
    肌钙蛋白T: "jigaiT",
    肌钙蛋白I: "jigaiI",
    BNP: "BNP",
    钠: "na",
    钾: "jia",
    氯: "lv",
    COdi2结合力: "CO2",

    尿素: "niaosu",
    肌酐: "jigan",
    尿酸: "niaosuan",

    Tdi3: "Tdi3",
    T4: "Tdi3",
    TSH: "TSH",
    抗甲状腺过氧化物酶抗体: "guoyanghuawumei",
    抗甲状腺球蛋白抗体: "qiudanbai",

    乙肝: "yigan",
    乙肝表面抗原: "biaomiankangyuan",
    乙肝表面抗体: "biaomiankangti",
    乙肝E抗原: "Ekangyuan",
    乙肝E抗体: "Ekangti",
    乙肝核心抗体: "hexinkangti",
    丙肝: "binggan",
    梅毒: "meidu",
    HIV: "HIV",

    PCT: "PCT",
    CRP: "CRP",

    脑脊液: "naojiye",
    ABETA: "ABETA",
    TLR: "TLR",
    NLR: "NLR",

    手术时间: "shoushushijian",
    手术方式: "shoushufangshi",
    药物治疗: "yaowuzhiliao",
    并发症: "bingfazheng",
    颅内感染: "luneiganran",
    肺炎: "feiyan",
    泌尿系感染: "miniaoxiganran",


    术后NIHSS: "shuhouNIHSS",
    术后GLASGOW: "shuhouGLASGOW",
    术后ADL: "shuhouADL",
    术后MRANKIN: "shuhouMRANKIN",
    术后血压: "shuhouxueya",

    出院血压: "chuyuanxueya",
    出院NIHSS: "chuyuanNIHSS",
    出院GLASGOW: "chuyuanGLASGOW",
    出院ADL: "chuyuanADL",
    出院MRANKIN: "chuyuanMRANKIN",
    出院MMSE: "chuyuanMMSE",
    出院LOTCA: "chuyuanLOTCA",


    两周血压: "di2zhouxueya",
    两周意识水平: "di2zhouyishishuiping",
    两周肢体运动肌力: "di2zhouzhitiyundongjili",
    两周感觉障碍: "di2zhouganjuezhangai",
    两周语言表达: "di2zhouyuyanbiaoda",
    两周神经反射: "di2zhoushenjingfanshe",
    两周病理征: "di2zhoubinglizheng",
    两周NIHSS: "di2zhouNIHSS",
    两周GLASGOW: "di2zhouGLASGOW",
    两周ADL: "di2zhouADL",
    两周MRANKIN: "di2zhouMRANKIN",


    三月血压: "di3yuexueya",
    三月意识水平: "di3yueyishishuiping",
    三月肢体运动肌力: "di3yuezhitiyundongjili",
    三月感觉障碍: "di3yueganjuezhangai",
    三月语言表达: "di3yueyuyanbiaoda",
    三月神经反射: "di3yueshenjingfanshe",
    三月病理征: "di3yuebinglizheng",
    三月NIHSS: "di3yueNIHSS",
    三月GLASGOW: "di3yueGLASGOW",
    三月ADL: "di3yueADL",
    三月MRANKIN: "di3yueMRANKIN",


    六月血压: "di6yuexueya",
    六月意识水平: "di6yueyishishuiping",
    六月肢体运动肌力: "di6yuezhitiyundongjili",
    六月感觉障碍: "di6yueganjuezhangai",
    六月语言表达: "di6yueyuyanbiaoda",
    六月神经反射: "di6yueshenjingfanshe",
    六月病理征: "di6yuebinglizheng",
    六月NIHSS: "di6yueNIHSS",
    六月GLASGOW: "di6yueGLASGOW",
    六月ADL: "di6yueADL",
    六月MRANKIN: "di6yueMRANKIN",
    六月MMSE: "di6yueMMSE",
    六月LOTCA: "di6yueLOTCA",

    一年血压: "di1nianxueya",
    一年意识水平: "di1nianyishishuiping",
    一年肢体运动肌力: "di1nianzhitiyundongjili",
    一年感觉障碍: "di1nianganjuezhangai",
    一年语言表达: "di1nianyuyanbiaoda",
    一年神经反射: "di1nianshenjingfanshe",
    一年病理征: "di1nianbinglizheng",
    一年NIHSS: "di1nianNIHSS",
    一年GLASGOW: "di1nianGLASGOW",
    一年ADL: "di1nianADL",
    一年MRANKIN: "di1nianMRANKIN",

    三年血压: "di3nianxueya",
    三年意识水平: "di3nianyishishuiping",
    三年肢体运动肌力: "di3nianzhitiyundongjili",
    三年感觉障碍: "di3nianganjuezhangai",
    三年语言表达: "di3nianyuyanbiaoda",
    三年神经反射: "di3nianshenjingfanshe",
    三年病理征: "di3nianbinglizheng",
    三年NIHSS: "di3nianNIHSS",
    三年GLASGOW: "di3nianGLASGOW",
    三年ADL: "di3nianADL",
    三年MRANKIN: "di3nianMRANKIN",

    五年血压: "di5nianxueya",
    五年意识水平: "di5nianyishishuiping",
    五年肢体运动肌力: "di5nianzhitiyundongjili",
    五年感觉障碍: "di5nianganjuezhangai",
    五年语言表达: "di5nianyuyanbiaoda",
    五年神经反射: "di5nianshenjingfanshe",
    五年病理征: "di5nianbinglizheng",
    五年NIHSS: "di5nianNIHSS",
    五年GLASGOW: "di5nianGLASGOW",
    五年ADL: "di5nianADL",
    五年MRANKIN: "di5nianMRANKIN",

    十年血压: "di10nianxueya",
    十年意识水平: "di10nianyishishuiping",
    十年肢体运动肌力: "di10nianzhitiyundongjili",
    十年感觉障碍: "di10nianganjuezhangai",
    十年语言表达: "di10nianyuyanbiaoda",
    十年神经反射: "di10nianshenjingfanshe",
    十年病理征: "di10nianbinglizheng",
    十年NIHSS: "di10nianNIHSS",
    十年GLASGOW: "di10nianGLASGOW",
    十年ADL: "di10nianADL",
    十年MRANKIN: "di10nianMRANKIN",

    康复锻炼:"kangfuduanlian",
    理疗:"liliao",
    康复时间:"kangfushijian"
};

export default formField;
